'use strict';
const crypto=require('node:crypto');
const cj=v=>Array.isArray(v)?`[${v.map(cj).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${cj(v[k])}`).join(',')}}`:JSON.stringify(v);
const sha=v=>crypto.createHash('sha256').update(typeof v==='string'?v:cj(v)).digest('hex');
const iso=v=>{const d=v instanceof Date?v:new Date(v);if(Number.isNaN(d.getTime()))throw new Error('time invalid');return d.toISOString()};
function createMatrixItemVersionOutbox({db,clock=()=>new Date()}={}){
 function row(r){return{id:r.id,entityType:r.entity_type,entityId:r.entity_id,entityVersion:r.entity_version,itemId:r.item_id,specificationId:r.specification_id,sourceVersionBindingId:r.source_version_binding_id,state:r.state,claimToken:r.claim_token,leaseExpiresAt:r.lease_expires_at,attemptCount:r.attempt_count,attentionIds:JSON.parse(r.attention_ids_json)}}
 function appendInTransaction(i={}){const payload={entityType:String(i.entityType),entityId:Number(i.entityId),entityVersion:Number(i.entityVersion),itemId:Number(i.itemId),specificationId:Number(i.specificationId)||0};const producerKey=sha(payload),ts=iso(clock());db.prepare(`INSERT OR IGNORE INTO matrix_item_version_events (producer_key,entity_type,entity_id,entity_version,item_id,specification_id,source_version_binding_id,actor_user_id,payload_fingerprint,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(producerKey,payload.entityType,payload.entityId,payload.entityVersion,payload.itemId,payload.specificationId||null,Number(i.sourceVersionBindingId)||null,Number(i.actorUserId),sha({...payload,sourceVersionBindingId:Number(i.sourceVersionBindingId)||0}),ts,ts);return row(db.prepare('SELECT * FROM matrix_item_version_events WHERE producer_key=?').get(producerKey))}
 function claim({ownerToken,leaseMs,now=clock()}={}){const ts=iso(now),lease=Number(leaseMs);if(!ownerToken||!Number.isInteger(lease)||lease<1000)throw new Error('claim input invalid');return db.transaction(()=>{db.prepare("UPDATE matrix_item_version_events SET state='pending',owner_token='',claim_token='',lease_expires_at='',updated_at=? WHERE state='claimed' AND lease_expires_at<=?").run(ts,ts);const r=db.prepare("SELECT * FROM matrix_item_version_events WHERE state='pending' AND attempt_count<3 ORDER BY id LIMIT 1").get();if(!r)return null;const ct=crypto.randomUUID(),exp=new Date(new Date(ts).getTime()+lease).toISOString();db.prepare("UPDATE matrix_item_version_events SET state='claimed',owner_token=?,claim_token=?,lease_expires_at=?,attempt_count=attempt_count+1,updated_at=? WHERE id=? AND state='pending'").run(String(ownerToken),ct,exp,ts,r.id);return row(db.prepare('SELECT * FROM matrix_item_version_events WHERE id=?').get(r.id))})()}
 function ack({eventId,claimToken,attentionIds=[],now=clock()}={}){const ts=iso(now);const q=db.prepare("UPDATE matrix_item_version_events SET state='delivered',attention_ids_json=?,updated_at=? WHERE id=? AND state='claimed' AND claim_token=?").run(cj(attentionIds.map(Number)),ts,Number(eventId),String(claimToken));if(q.changes!==1){const r=db.prepare('SELECT * FROM matrix_item_version_events WHERE id=?').get(Number(eventId));if(r?.state==='delivered')return row(r);throw new Error('outbox claim mismatch')}return row(db.prepare('SELECT * FROM matrix_item_version_events WHERE id=?').get(Number(eventId)))}
 function nack({eventId,claimToken,outcome,errorCode='',now=clock()}={}){if(!['definite_failure','ambiguous','lease_expired'].includes(outcome))throw new Error('outcome invalid');const r=db.prepare('SELECT * FROM matrix_item_version_events WHERE id=?').get(Number(eventId));if(!r||r.state!=='claimed'||r.claim_token!==String(claimToken))throw new Error('outbox claim mismatch');const state=outcome==='lease_expired'?'pending':outcome==='definite_failure'&&r.attempt_count<3?'pending':'manual_review';db.prepare("UPDATE matrix_item_version_events SET state=?,owner_token='',claim_token='',lease_expires_at='',last_error_code=?,updated_at=? WHERE id=?").run(state,String(errorCode),iso(now),r.id);return row(db.prepare('SELECT * FROM matrix_item_version_events WHERE id=?').get(r.id))}
 return{appendInTransaction,claim,ack,nack};
}
module.exports={createMatrixItemVersionOutbox};
