'use strict';
const crypto = require('node:crypto');
function cj(v){if(Array.isArray(v))return`[${v.map(cj).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${cj(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function sha(v){return crypto.createHash('sha256').update(typeof v==='string'?v:cj(v)).digest('hex')}
function tok(v,l,m=2000){const x=String(v??'').trim();if(!x)throw new Error(`${l} required`);if(x.length>m)throw new Error(`${l} too long`);return x}
function parse(v,f){try{return JSON.parse(v)}catch{return f}}
function createMatrixKnowledgeLedger({db,clock=()=>new Date(),taskSupervisor=null}={}){
  const now=()=>{const v=clock();return(v instanceof Date?v:new Date(v)).toISOString()};
  const candidate=r=>({id:r.id,sourceEventIds:parse(r.source_event_ids_json,[]),sourceAcceptanceId:r.source_acceptance_id,statement:r.statement,predicates:parse(r.predicates_json,{}),exclusions:parse(r.exclusions_json,[]),unresolved:parse(r.unresolved_json,[]),conflicts:parse(r.conflicts_json,[]),contentHash:r.content_hash,status:r.status,actorUserId:r.actor_user_id});
  const rule=r=>({id:r.id,candidateId:r.candidate_id,version:r.version,scope:r.scope,scopePredicates:parse(r.scope_predicates_json,{}),exclusions:parse(r.exclusions_json,[]),statement:r.statement,unresolved:parse(r.unresolved_json,[]),state:r.state,supersedesRuleId:r.supersedes_rule_id});
  function command(key,request,fn){key=tok(key,'idempotency key',200);const fp=sha(request);return db.transaction(()=>{const old=db.prepare('SELECT * FROM matrix_knowledge_commands WHERE idempotency_key=?').get(key);if(old){if(old.request_fingerprint!==fp)throw new Error('knowledge idempotency conflict');return parse(old.result_json,null)}const out=fn(key);db.prepare('INSERT INTO matrix_knowledge_commands VALUES (?,?,?,?)').run(key,fp,cj(out),now());return out})()}
  function createCandidate(i={}){const sourceEventIds=[...new Set((i.sourceEventIds||[]).map(Number))].filter(Number.isInteger).sort((a,b)=>a-b);const request={op:'create',sourceEventIds,sourceAcceptanceId:i.sourceAcceptanceId?Number(i.sourceAcceptanceId):null,statement:tok(i.statement,'statement'),predicates:i.predicates||{},exclusions:i.exclusions||[],unresolved:i.unresolved||[],conflicts:i.conflicts||[],actorUserId:Number(i.actorUserId)};return command(i.idempotencyKey,request,key=>{for(const id of sourceEventIds)if(!db.prepare('SELECT id FROM matrix_conversation_events WHERE id=?').get(id))throw new Error('source event not found');if(!sourceEventIds.length&&!request.sourceAcceptanceId)throw new Error('source provenance required');const contentHash=sha({statement:request.statement,predicates:request.predicates,exclusions:request.exclusions,unresolved:request.unresolved,conflicts:request.conflicts,sourceEventIds});const ts=now();const info=db.prepare(`INSERT INTO matrix_knowledge_candidates (source_event_ids_json,source_acceptance_id,statement,predicates_json,exclusions_json,unresolved_json,conflicts_json,content_hash,actor_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(cj(sourceEventIds),request.sourceAcceptanceId,request.statement,cj(request.predicates),cj(request.exclusions),cj(request.unresolved),cj(request.conflicts),contentHash,request.actorUserId,ts,ts);const row=db.prepare('SELECT * FROM matrix_knowledge_candidates WHERE id=?').get(info.lastInsertRowid);let decisionTaskId=null;if(taskSupervisor)decisionTaskId=taskSupervisor.ensureTask({taskType:'knowledge_scope',ownerRole:'foreign_trade_crm_admin',channel:'bill',dueAt:ts,bindings:{candidateId:row.id},blocker:'scope_required',nextAction:'Choose A-D scope',evidenceIds:sourceEventIds.map(id=>`conversation:${id}`),idempotencyKey:`${key}:task`}).id;return{kind:'created',candidate:candidate(row),decisionTaskId}})}
  function insertRule(c,scope,predicates,exclusions,actorUserId,supersedes=null){const ts=now();const info=db.prepare(`INSERT INTO matrix_knowledge_rules (candidate_id,scope,scope_predicates_json,exclusions_json,statement,unresolved_json,supersedes_rule_id,actor_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(c.id,scope,cj(predicates),cj(exclusions),c.statement,c.unresolved_json,supersedes,actorUserId,ts,ts);return db.prepare('SELECT * FROM matrix_knowledge_rules WHERE id=?').get(info.lastInsertRowid)}
  function decideScope(i={}){const request={op:'scope',candidateId:Number(i.candidateId),expectedContentHash:tok(i.expectedContentHash,'content hash'),scope:tok(i.scope,'scope',1),scopePredicates:i.scopePredicates||{},actorUserId:Number(i.actorUserId),bindingId:tok(i.bindingId,'binding id'),chatId:tok(i.chatId,'chat id'),cardEventId:tok(i.cardEventId,'card event id')};if(!['A','B','C','D'].includes(request.scope))throw new Error('invalid scope');return command(i.idempotencyKey,request,key=>{const c=db.prepare('SELECT * FROM matrix_knowledge_candidates WHERE id=?').get(request.candidateId);if(!c)throw new Error('candidate not found');if(c.content_hash!==request.expectedContentHash)throw new Error('candidate content hash mismatch');if(request.scope==='A'&&!Number.isInteger(Number(request.scopePredicates.itemId)))throw new Error('A scope item id required');if(request.scope==='D'){db.prepare("UPDATE matrix_knowledge_candidates SET status='broader_review',updated_at=? WHERE id=?").run(now(),c.id);let broaderReviewTaskId=null;if(taskSupervisor)broaderReviewTaskId=taskSupervisor.ensureTask({taskType:'knowledge_general_review',ownerRole:'foreign_trade_crm_admin',channel:'bill',dueAt:now(),bindings:{candidateId:c.id},blocker:'second_review_required',nextAction:'Confirm exclusions and evidence',evidenceIds:[],idempotencyKey:`${key}:task`}).id;return{candidate:candidate(db.prepare('SELECT * FROM matrix_knowledge_candidates WHERE id=?').get(c.id)),rule:null,broaderReviewTaskId}}const r=insertRule(c,request.scope,request.scopePredicates,parse(c.exclusions_json,[]),request.actorUserId);db.prepare("UPDATE matrix_knowledge_candidates SET status='scoped',updated_at=? WHERE id=?").run(now(),c.id);return{candidate:candidate(db.prepare('SELECT * FROM matrix_knowledge_candidates WHERE id=?').get(c.id)),rule:rule(r),broaderReviewTaskId:null}})}
  function confirmGeneral(i={}){const request={op:'general',candidateId:Number(i.candidateId),expectedContentHash:tok(i.expectedContentHash,'content hash'),exclusions:i.exclusions||[],supportingCaseIds:i.supportingCaseIds||[],explicitOwnerDeclaration:i.explicitOwnerDeclaration===true,actorUserId:Number(i.actorUserId),bindingId:tok(i.bindingId,'binding id'),chatId:tok(i.chatId,'chat id'),cardEventId:tok(i.cardEventId,'card event id')};if(!request.supportingCaseIds.length&&!request.explicitOwnerDeclaration)throw new Error('supporting case or explicit owner declaration required');return command(i.idempotencyKey,request,()=>{const c=db.prepare('SELECT * FROM matrix_knowledge_candidates WHERE id=?').get(request.candidateId);if(!c)throw new Error('candidate not found');if(c.content_hash!==request.expectedContentHash)throw new Error('candidate content hash mismatch');const r=insertRule(c,'D',{},request.exclusions,request.actorUserId);db.prepare("UPDATE matrix_knowledge_candidates SET status='scoped',updated_at=? WHERE id=?").run(now(),c.id);return{rule:rule(r)}})}
  function supersede(i={}){const request={op:'supersede',ruleId:Number(i.ruleId),expectedVersion:Number(i.expectedVersion),replacementCandidateId:Number(i.replacementCandidateId),actorUserId:Number(i.actorUserId)};return command(i.idempotencyKey,request,()=>{const old=db.prepare('SELECT * FROM matrix_knowledge_rules WHERE id=?').get(request.ruleId);if(!old)throw new Error('rule not found');if(old.version!==request.expectedVersion||old.state!=='active')throw new Error('stale rule version');const c=db.prepare('SELECT * FROM matrix_knowledge_candidates WHERE id=?').get(request.replacementCandidateId);if(!c)throw new Error('replacement candidate not found');db.prepare("UPDATE matrix_knowledge_rules SET state='superseded',version=version+1,updated_at=? WHERE id=?").run(now(),old.id);const next=insertRule(c,old.scope,parse(old.scope_predicates_json,{}),parse(old.exclusions_json,[]),request.actorUserId,old.id);return{previousRule:rule(db.prepare('SELECT * FROM matrix_knowledge_rules WHERE id=?').get(old.id)),rule:rule(next)}})}
  function matchScenario({itemId,specificationId}={}){const item=Number(itemId);return db.prepare("SELECT * FROM matrix_knowledge_rules WHERE state='active' ORDER BY id").all().filter(r=>{const p=parse(r.scope_predicates_json,{});if(r.scope==='A')return Number(p.itemId)===item;if(p.itemId&&Number(p.itemId)!==item)return false;if(p.specificationId&&Number(p.specificationId)!==Number(specificationId))return false;return Object.keys(p).every(k=>['itemId','specificationId'].includes(k))}).map(rule)}
  function refreshAttention({itemId,specificationId,sourceEventId,idempotencyKey}={}){return command(idempotencyKey,{op:'attention',itemId:Number(itemId),specificationId:Number(specificationId)||null,sourceEventId:Number(sourceEventId)||null},()=>{const rows=[];for(const r of matchScenario({itemId,specificationId})){const ch=sha({ruleId:r.id,version:r.version,itemId:Number(itemId),specificationId:Number(specificationId)||0});db.prepare(`INSERT OR IGNORE INTO matrix_knowledge_attention (rule_id,item_id,specification_id,source_event_id,content_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?)`).run(r.id,Number(itemId),Number(specificationId)||null,Number(sourceEventId)||null,ch,now(),now());rows.push(db.prepare('SELECT * FROM matrix_knowledge_attention WHERE rule_id=? AND item_id=? AND content_hash=?').get(r.id,Number(itemId),ch))}return rows})}
  return{createCandidate,decideScope,confirmGeneral,supersede,matchScenario,refreshAttention};
}
module.exports={createMatrixKnowledgeLedger};
