#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
function emit(body,code=0){fs.writeSync(code===0?1:2,`${JSON.stringify(body,null,2)}\n`);process.exit(code)}
function blocked(reason){emit({status:'blocked',reason},3)}
function positive(value,name){const n=Number(value);if(!Number.isFinite(n)||n<=0)blocked(`${name} must be a finite number > 0`);return n}
function round(value,digits=6){const factor=10**digits;return Math.round((value+Number.EPSILON)*factor)/factor}
const inputPath=process.argv[2],profilePath=process.argv[3]||'/refs/packet-route-profiles.json';if(!inputPath)blocked('usage: packet-route.js <input.json> [profiles.json]');
let input,registry;try{input=JSON.parse(fs.readFileSync(inputPath,'utf8'));registry=JSON.parse(fs.readFileSync(profilePath,'utf8'))}catch(error){blocked(`unable to read route input/profile: ${error.message}`)}
const profile=(registry.profiles||[]).find(row=>row.id===String(input.profile_id||'').trim());if(!profile)blocked('profile_id must match a reviewed route profile');
const productPrice=positive(input.product_price_yuan_kg,'product_price_yuan_kg'),itemWeight=positive(input.item_weight_kg??input.net_weight_kg,'item_weight_kg'),allocationWeight=positive(input.allocation_weight_kg??input.net_weight_kg,'allocation_weight_kg'),exchangeRate=positive(input.exchange_rate_yuan_per_usd,'exchange_rate_yuan_per_usd'),fixed=profile.fixed_charges_yuan||{},baseTrucking=positive(fixed.trucking,'profile.fixed_charges_yuan.trucking');
let truckingSurcharge=0;if(profile.trucking_surcharge&&allocationWeight>Number(profile.trucking_surcharge.threshold_kg))truckingSurcharge=((allocationWeight-Number(profile.trucking_surcharge.threshold_kg))/1000)*Number(profile.trucking_surcharge.yuan_per_excess_ton);
const trucking=baseTrucking+truckingSurcharge,declaration=positive(fixed.declaration,'profile.fixed_charges_yuan.declaration'),localPort=positive(fixed.local_port,'profile.fixed_charges_yuan.local_port'),operation=positive(fixed.operation,'profile.fixed_charges_yuan.operation'),originCharges=trucking+declaration+localPort+operation,originAllocation=originCharges/allocationWeight,fobYuanKg=productPrice+originAllocation,fobUsdKg=fobYuanKg/exchangeRate,summary=String(input.item_summary||'本批货物').trim();
const reviewMessage=[`请复核以下FOB起运费用：${summary}，暂按${profile.label_cn}（${profile.shipping_mode}）估算。`,`本品项：${round(itemWeight,3)}kg；费用分摊总货量：${round(allocationWeight,3)}kg；起运港：${profile.origin_port_cn}。`,`当前历史费用：拖车RMB ${round(trucking,2)}、报关RMB ${round(declaration,2)}、港杂/local RMB ${round(localPort,2)}、操作费RMB ${round(operation,2)}，合计RMB ${round(originCharges,2)}。`,'请确认上述金额现在是否有效，并补充未包含项目、计费单位、有效期及所需单证。'].join('\n');
emit({status:'internal_estimate',formula_version:'matrix-route-v1',profile_version:registry.schema_version,ledger_updated_on:registry.ledger_updated_on,trade_term:'FOB',origin_port:profile.origin_port,shipping_mode:profile.shipping_mode,evidence_class:profile.evidence_class,normalized_input:{profile_id:profile.id,product_price_yuan_kg:productPrice,item_weight_kg:itemWeight,allocation_weight_kg:allocationWeight,exchange_rate_yuan_per_usd:exchangeRate,item_summary:summary},intermediate:{product_value_yuan:round(productPrice*itemWeight),trucking_yuan:round(trucking),trucking_surcharge_yuan:round(truckingSurcharge),declaration_yuan:round(declaration),local_port_yuan:round(localPort),operation_yuan:round(operation),origin_charges_yuan:round(originCharges),origin_allocation_yuan_kg:round(originAllocation)},result:{fob_yuan_kg:round(fobYuanKg),fob_usd_kg:round(fobUsdKg),total_fob_yuan:round(fobYuanKg*itemWeight),total_fob_usd:round((fobYuanKg*itemWeight)/exchangeRate)},formulas:['origin_charges_yuan = trucking + declaration + local_port + operation','origin_allocation_yuan_kg = origin_charges_yuan / allocation_weight_kg','fob_yuan_kg = product_price_yuan_kg + origin_allocation_yuan_kg','fob_usd_kg = fob_yuan_kg / exchange_rate_yuan_per_usd'],unresolved_assumptions:profile.unresolved_assumptions||[],source:profile.source,requires_forwarder_review:true,forwarder_review_message_cn:reviewMessage});
